//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStart.Resources.Pages.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStart.Resources.Pages.Home.ContactPage", typeof(ContactPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press/Business Contact: &lt;span class=&quot;opensans_400&quot;&gt;&lt;a href=&quot;&quot;&gt;company-business-inbox@domain.com&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string DigitalBusinessContact {
            get {
                return ResourceManager.GetString("DigitalBusinessContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Contacts.
        /// </summary>
        public static string DigitalContactHeader {
            get {
                return ResourceManager.GetString("DigitalContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Account: &lt;span class=&quot;opensans_400&quot;&gt;&lt;a href=&quot;&quot;&gt;facebook.com/nstart&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string DigitalFacebookContact {
            get {
                return ResourceManager.GetString("DigitalFacebookContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Contact: &lt;span class=&quot;opensans_400&quot;&gt;&lt;a href=&quot;&quot;&gt;support@domain.com&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string DigitalSupportContact {
            get {
                return ResourceManager.GetString("DigitalSupportContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account: &lt;span class=&quot;opensans_400&quot;&gt;&lt;a href=&quot;&quot;&gt;@nstart&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string DigitalTwitterContact {
            get {
                return ResourceManager.GetString("DigitalTwitterContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Contact: &lt;span class=&quot;opensans_400&quot;&gt;&lt;a href=&quot;&quot;&gt;users-inbox@domain.com&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        public static string DigitalUsersContact {
            get {
                return ResourceManager.GetString("DigitalUsersContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the means of contacts (digital or IRL) that we are currently using..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/ContactPage.
        /// </summary>
        public static string PageRoute {
            get {
                return ResourceManager.GetString("PageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset Drive 123. Vice City, Continental Country.
        /// </summary>
        public static string PhysicalAddress {
            get {
                return ResourceManager.GetString("PhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Contacts.
        /// </summary>
        public static string PhysicalContactHeader {
            get {
                return ResourceManager.GetString("PhysicalContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: &lt;span class=&quot;opensans_400&quot;&gt; +0 (123)-456-7890&lt;/span&gt;.
        /// </summary>
        public static string PhysicalPhone {
            get {
                return ResourceManager.GetString("PhysicalPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O. Box: &lt;span class=&quot;opensans_400&quot;&gt;&lt;/span&gt;.
        /// </summary>
        public static string PhysicalPostOfficeBox {
            get {
                return ResourceManager.GetString("PhysicalPostOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string SyndicationId {
            get {
                return ResourceManager.GetString("SyndicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the means of contacts (digital or IRL) that we are currently using..
        /// </summary>
        public static string TwitterDescription {
            get {
                return ResourceManager.GetString("TwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImage {
            get {
                return ResourceManager.GetString("TwitterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImageAlt {
            get {
                return ResourceManager.GetString("TwitterImageAlt", resourceCulture);
            }
        }
    }
}
