//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStart.Resources.Pages.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStart.Resources.Pages.Home.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the Adventure.
        /// </summary>
        public static string History_FirstStep_Header {
            get {
                return ResourceManager.GetString("History_FirstStep_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string History_FirstStep_Text {
            get {
                return ResourceManager.GetString("History_FirstStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our current face.
        /// </summary>
        public static string History_ForthStep_Header {
            get {
                return ResourceManager.GetString("History_ForthStep_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string History_ForthStep_Text {
            get {
                return ResourceManager.GetString("History_ForthStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first hit.
        /// </summary>
        public static string History_SecondStep_Header {
            get {
                return ResourceManager.GetString("History_SecondStep_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string History_SecondStep_Text {
            get {
                return ResourceManager.GetString("History_SecondStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A struggling studio.
        /// </summary>
        public static string History_ThirdStep_Header {
            get {
                return ResourceManager.GetString("History_ThirdStep_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string History_ThirdStep_Text {
            get {
                return ResourceManager.GetString("History_ThirdStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our History.
        /// </summary>
        public static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home.
        /// </summary>
        public static string PageRoute {
            get {
                return ResourceManager.GetString("PageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Studio.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NStart.
        /// </summary>
        public static string StudioName {
            get {
                return ResourceManager.GetString("StudioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A easier way to tell the world about your videogames studio.
        /// </summary>
        public static string StudioSlogan {
            get {
                return ResourceManager.GetString("StudioSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A basic NStart project.
        /// </summary>
        public static string TwitterDescription {
            get {
                return ResourceManager.GetString("TwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImage {
            get {
                return ResourceManager.GetString("TwitterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImageAlt {
            get {
                return ResourceManager.GetString("TwitterImageAlt", resourceCulture);
            }
        }
    }
}
