//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStart.Resources.Pages.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AwardsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AwardsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStart.Resources.Pages.Company.AwardsPage", typeof(AwardsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;Hitch Gamer: How to make a compelling indie game. 2009.&lt;/a&gt;.
        /// </summary>
        public static string Articles_1 {
            get {
                return ResourceManager.GetString("Articles_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;Future Innovations: Top 10 tech stacks. 2011.&lt;/a&gt;.
        /// </summary>
        public static string Articles_2 {
            get {
                return ResourceManager.GetString("Articles_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;OpenGaming: The legacy of a legend in our industry. 2015.&lt;/a&gt;.
        /// </summary>
        public static string Articles_3 {
            get {
                return ResourceManager.GetString("Articles_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;FakeSite: The unspoken struggle of the video game industry. 2018.&lt;/a&gt;.
        /// </summary>
        public static string Articles_4 {
            get {
                return ResourceManager.GetString("Articles_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;2008: Award to innovation.&lt;/a&gt;.
        /// </summary>
        public static string Awards_1 {
            get {
                return ResourceManager.GetString("Awards_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;2009: Game of the Year award. Category: Sound design. Result: Winner.&lt;/a&gt;.
        /// </summary>
        public static string Awards_2 {
            get {
                return ResourceManager.GetString("Awards_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt; 2011: RadSpot&apos;s E3 Best Game Award nominee.&lt;/a&gt;.
        /// </summary>
        public static string Awards_3 {
            get {
                return ResourceManager.GetString("Awards_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;2013: Best European studio to work in.&lt;/a&gt;.
        /// </summary>
        public static string Awards_4 {
            get {
                return ResourceManager.GetString("Awards_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;&quot;&gt;2017: Best resurgence of a studio.&lt;/a&gt;.
        /// </summary>
        public static string Awards_5 {
            get {
                return ResourceManager.GetString("Awards_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Awards &amp; Recognitions.
        /// </summary>
        public static string AwardsHeader {
            get {
                return ResourceManager.GetString("AwardsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AwardsIntroduction {
            get {
                return ResourceManager.GetString("AwardsIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured news Articles.
        /// </summary>
        public static string FeaturedArticlesHeader {
            get {
                return ResourceManager.GetString("FeaturedArticlesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of all the awards and recognitions that our studo has won..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Company/AwardsPage.
        /// </summary>
        public static string PageRoute {
            get {
                return ResourceManager.GetString("PageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards &amp; Recognitions.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string SyndicationId {
            get {
                return ResourceManager.GetString("SyndicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of all the awards and recognitions that our studo has won..
        /// </summary>
        public static string TwitterDescription {
            get {
                return ResourceManager.GetString("TwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImage {
            get {
                return ResourceManager.GetString("TwitterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImageAlt {
            get {
                return ResourceManager.GetString("TwitterImageAlt", resourceCulture);
            }
        }
    }
}
