//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStart.Resources.Pages.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStart.Resources.Pages.Company.ProjectsPage", typeof(ProjectsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videogame Projects.
        /// </summary>
        public static string OurGamesSection {
            get {
                return ResourceManager.GetString("OurGamesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comprehensive list of all the videogame projects that we have developed..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Company/ProjectsPage.
        /// </summary>
        public static string PageRoute {
            get {
                return ResourceManager.GetString("PageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Projects.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProjectsIntroduction {
            get {
                return ResourceManager.GetString("ProjectsIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string SyndicationId {
            get {
                return ResourceManager.GetString("SyndicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestProject_ProjectDescription {
            get {
                return ResourceManager.GetString("TestProject_ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NStart.
        /// </summary>
        public static string TestProject_ProjectDeveloper {
            get {
                return ResourceManager.GetString("TestProject_ProjectDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        public static string TestProject_ProjectDeveloper_Header {
            get {
                return ResourceManager.GetString("TestProject_ProjectDeveloper_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of the Dead.
        /// </summary>
        public static string TestProject_ProjectName {
            get {
                return ResourceManager.GetString("TestProject_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake Publishing LTD.
        /// </summary>
        public static string TestProject_ProjectPublisher {
            get {
                return ResourceManager.GetString("TestProject_ProjectPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string TestProject_ProjectPublisher_Header {
            get {
                return ResourceManager.GetString("TestProject_ProjectPublisher_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Game!.
        /// </summary>
        public static string TestProjectDeliverStatus {
            get {
                return ResourceManager.GetString("TestProjectDeliverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        public static string TestProjectGameMode_SinglePlayer {
            get {
                return ResourceManager.GetString("TestProjectGameMode_SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Date: 4/7/2008.
        /// </summary>
        public static string TestProjectLaunchDate {
            get {
                return ResourceManager.GetString("TestProjectLaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Page.
        /// </summary>
        public static string TestProjectPageLink {
            get {
                return ResourceManager.GetString("TestProjectPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game modes.
        /// </summary>
        public static string TestProjectsGameModeHeader {
            get {
                return ResourceManager.GetString("TestProjectsGameModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Technical Sheet.
        /// </summary>
        public static string TestProjectSheetHeader {
            get {
                return ResourceManager.GetString("TestProjectSheetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6GB DDR4 @@ 3200MHz.
        /// </summary>
        public static string TestProjectSpecifications_Memory {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory:.
        /// </summary>
        public static string TestProjectSpecifications_Memory_Header {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Memory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x64 capable processor @@ 2.56GHz.
        /// </summary>
        public static string TestProjectSpecifications_Processor {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor:.
        /// </summary>
        public static string TestProjectSpecifications_Processor_Header {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Processor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20GB.
        /// </summary>
        public static string TestProjectSpecifications_Storage {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage:.
        /// </summary>
        public static string TestProjectSpecifications_Storage_Header {
            get {
                return ResourceManager.GetString("TestProjectSpecifications_Storage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Specifications.
        /// </summary>
        public static string TestProjectSpecificationsHeader {
            get {
                return ResourceManager.GetString("TestProjectSpecificationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Platforms.
        /// </summary>
        public static string TestProjectTargetPlatformsHeader {
            get {
                return ResourceManager.GetString("TestProjectTargetPlatformsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comprehensive list of all the videogame projects that we have developed..
        /// </summary>
        public static string TwitterDescription {
            get {
                return ResourceManager.GetString("TwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImage {
            get {
                return ResourceManager.GetString("TwitterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImageAlt {
            get {
                return ResourceManager.GetString("TwitterImageAlt", resourceCulture);
            }
        }
    }
}
