//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStart.Resources.Pages.Company {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStart.Resources.Pages.Company.TeamPage", typeof(TeamPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our current full-time team members and some of our most frequent contractors and outside developers..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our team.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Company/TeamPage.
        /// </summary>
        public static string PageRoute {
            get {
                return ResourceManager.GetString("PageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SyndicationId {
            get {
                return ResourceManager.GetString("SyndicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Mail Inbox: &lt;a href=&quot;&quot;&gt;fakeuser@domain.com&lt;/a&gt;..
        /// </summary>
        public static string TeammateA_Contact_MailInbox {
            get {
                return ResourceManager.GetString("TeammateA_Contact_MailInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours: 6AM - 4PM (Every Day)..
        /// </summary>
        public static string TeammateA_Contact_OfficeHours {
            get {
                return ResourceManager.GetString("TeammateA_Contact_OfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account: &lt;a href=&quot;&quot;&gt;@fakeuser&lt;/a&gt;..
        /// </summary>
        public static string TeammateA_Contact_TwitterAccount {
            get {
                return ResourceManager.GetString("TeammateA_Contact_TwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeammateA_Description {
            get {
                return ResourceManager.GetString("TeammateA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrick Walker.
        /// </summary>
        public static string TeammateA_Name {
            get {
                return ResourceManager.GetString("TeammateA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrick Walker&apos;s picture.
        /// </summary>
        public static string TeammateA_Picture_Alt {
            get {
                return ResourceManager.GetString("TeammateA_Picture_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrick Walker&apos;s picture.
        /// </summary>
        public static string TeammateA_Picture_Title {
            get {
                return ResourceManager.GetString("TeammateA_Picture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NStart CEO.
        /// </summary>
        public static string TeammateA_Position {
            get {
                return ResourceManager.GetString("TeammateA_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Mail Inbox: &lt;a href=&quot;&quot;&gt;fakeuser@domain.com&lt;/a&gt;..
        /// </summary>
        public static string TeammateB_Contact_MailInbox {
            get {
                return ResourceManager.GetString("TeammateB_Contact_MailInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours: 10AM - 2PM (Monday to Friday)..
        /// </summary>
        public static string TeammateB_Contact_OfficeHours {
            get {
                return ResourceManager.GetString("TeammateB_Contact_OfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeammateB_Description {
            get {
                return ResourceManager.GetString("TeammateB_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megan Bailey.
        /// </summary>
        public static string TeammateB_Name {
            get {
                return ResourceManager.GetString("TeammateB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megan Bailey&apos;s picture.
        /// </summary>
        public static string TeammateB_Picture_Alt {
            get {
                return ResourceManager.GetString("TeammateB_Picture_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megan Bailey&apos;s picture.
        /// </summary>
        public static string TeammateB_Picture_Title {
            get {
                return ResourceManager.GetString("TeammateB_Picture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NStart CFO.
        /// </summary>
        public static string TeammateB_Position {
            get {
                return ResourceManager.GetString("TeammateB_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account: &lt;a href=&quot;&quot;&gt;@fakeuser&lt;/a&gt;..
        /// </summary>
        public static string TeammateB_TwitterAccount {
            get {
                return ResourceManager.GetString("TeammateB_TwitterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our current full-time team members and some of our most frequent contractors and outside developers..
        /// </summary>
        public static string TwitterDescription {
            get {
                return ResourceManager.GetString("TwitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImage {
            get {
                return ResourceManager.GetString("TwitterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwitterImageAlt {
            get {
                return ResourceManager.GetString("TwitterImageAlt", resourceCulture);
            }
        }
    }
}
