name: .NET Core Test Only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_only:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Test all the projects
      run: dotnet test --no-restore --verbosity normal
